# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mdb-socials' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mdb-socials
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Analytics'
  pod 'Firebase/Storage'

  target 'mdb-socialsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mdb-socialsUITests' do
    # Pods for testing
  end

end
